DELETE http://localhost:8080/projects/1
Content-Type: application/json

{
  "userId": 1
}

###

###
POST http://localhost:3001/api/login
content-type: application/json

{
  "username": "d@d.d",
  "password": "d"
}

###
GET http://localhost:3001/api/posts
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIzLCJuYW1lIjoiRHV5IiwiZW1haWwiOiJkQGQuZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYwNjc5NjAwMH0.W9SFcFS5I602iBIGkOpwKwm_eXLXg3XxEG99BLhbRFI

###

###

GET http://localhost:3001/api/articles?p=5

###

POST http://localhost:3001/api/article
content-type: application/json

{
    "title": "Từ vựng Tiếng Anh về dụng cụ học tập",
    "thumbnail": "https://www.voca.vn/assets/img/news/market-store-icon-1540363857.jpg",
    "short_content": "Tổng hợp tất tần tật từ vựng tiếng anh về dụng cụ học tập được trình bày sinh động với hình ảnh, ví dụ, âm thanh giúp bạn dễ dàng ghi nhớ và ứng dụng.",
    "contents": "Danh sách từ vựng Tiếng Anh về dụng cụ học tập",
    "category_name": "Từ vựng tiếng Anh theo chủ đề"
}

###

PUT http://localhost:3001/api/article
content-type: application/json

{
  "id": "JLDDsx1AO3MdG65ij2GY",
  "title": "Từ vựng về các cửa hàng",
  "thumbnail": "https://www.voca.vn/assets/img/news/market-store-icon-1540363857.jpg",
  "short_content": "Tổng hợp tất tần tật từ vựng tiếng anh về các cửa hàng được trình bày sinh động với hình ảnh, ví dụ, âm thanh giúp bạn dễ dàng ghi nhớ và ứng dụng.",
  "contents": "Danh sách từ vựng:",
  "category_name": "Từ vựng tiếng Anh theo chủ đề"
}

###

GET http://localhost:3001/users

###
GET http://localhost:3001/articles


###
POST http://localhost:3001/articles/add
content-type: application/json

{
    "category_name": "Tin vit",
    "thumbnail": "https://nghesiviet.vn/storage/files/7/kieutrinh/hot-girl-kieu-trinh.jpg",
    "title": "Tiểu Sử Hot Girl Kiều Trinh",
    "short_content": "Hot girl Kiều Trinh tên đầy đủ là Nguyễn Hoàng Kiều Trinh. ",
    "contents": "Cô sinh năm 1994, hiện đang là sinh viên năm cuối chuyên ngành Marketing của Trường Quốc tế PSB College. Cô gái Sài Gòn được giới trẻ biết đến qua phim ngắn của Chi Pu cùng các bộ ảnh với vai trò model trên nhiều tạp chí, trang tin điện tử."
}

###
GET http://localhost:3001/articles/5fd2e9c0f13c813b9001213e


###
DELETE http://localhost:3001/articles/5fd2e9c0f13c813b9001213e

###

POST http://localhost:3001/articles/update/5fd44dfd16546e3914a9d6eb
content-type: application/json

{
    "category_name": "Tin vit Tin vit Tin vit",
    "thumbnail": "https://znews-photo.zadn.vn/w660/Uploaded/mdf_drkydd/2018_04_10/2013.jpg",
    "title": "Kiều Trinh: Từ 'cô gái trà sữa' tới hot girl theo phong cách sexy",
    "short_content": "Hot girl Kiều Trinh tên đầy đủ là Nguyễn Hoàng Kiều Trinh. ",
    "contents": "https://zingnews.vn/kieu-trinh-tu-co-gai-tra-sua-toi-hot-girl-theo-phong-cach-sexy-post833163.html"
}

###
GET http://localhost:3001/upload/sliderbar

###
GET http://localhost:3001/upload/5fd71aafcfcba631c09b7124

###
DELETE http://localhost:3001/upload/5fd7124b78295d2878339efe

###========================================================================================
###
GET http://localhost:3001/user/students

###
GET http://localhost:3001/user/students/5fdb1a64205db83db4a32000

###
POST http://localhost:3001/user/add
content-type: application/json

{
  "account" : "phamthao", 
  "password" : "123456", 
  "role" : "student", 

  "local_id" : "TC62", 
  "fullname" : "Phạm Phương Thảo", 
  "avatar" : "avatar_250x250_UserName.jpg",
  "date_of_birth" : "Wed, 21 Oct 2015 10:21:30 GMT", 
  "phone_number" : "123456789", 
  "address" : "xxxxxxaddress", 
  "email" : "phamthao@gmail.com", 
  "facebook" : "xxxxxxfacebook", 
  "zoom_id" : "xxxxxxzoom_id", 
  "skype_id" : "xxxxxxskype_id", 

  "parent_name" : "xxxxxxparent_name", 
  "parent_phone" : "xxxxxxparent_phone", 
  "parent_email" : "xxxxxxparent_email", 
  "date_join" : "Wed, 21 Oct 2015 18:27:50 GMT",
  "notes":"Lười học"
}
###
POST http://localhost:3001/user/add
content-type: application/json

{
  "account" : "d@d", 
  "password" : "123", 
  "role" : "admin", 

  "local_id" : "TC01", 
  "fullname" : "Doan Khanh Duy", 
  "date_of_birth" : "Wed, 21 Oct 2015 10:21:30 GMT", 
  "phone_number" : "123456789", 
  "address" : "xxxxxxaddress", 
  "email" : "d@d.d", 
  "facebook" : "xxxxxxfacebook", 
  "zoom_id" : "xxxxxxzoom_id", 
  "skype_id" : "xxxxxxskype_id", 

  "parent_name" : "xxxxxxparent_name", 
  "parent_phone" : "xxxxxxparent_phone", 
  "parent_email" : "xxxxxxparent_email", 
  "date_join" : "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
post  http://localhost:3001/user/update/5fdb1a64205db83db4a32000
content-type: application/json

{
  "avatar" : "avatar_250x250_UserName.jpg"
}
## ======================================================================================
###
post http://localhost:3001/courses/add
content-type: application/json

{
    "course_name": "PANKIDS 6",
    "duration_month": "6 THÁNG",
    "number_lessons": "30",
    "tuition_fee": "8120000",
    "notes": "FUN FOR STARTERS 6"
}

###
GET http://localhost:3001/courses


//======================================================================================
  // res.req.body =>
  // _id: '5fdb1a86205db83db4a32001',
  // account: 'phuongvu',
  // address: 'xxxxxxaddress',
  // avatar: 'stock-photo-smiling-female-entrepreneur-working-from-home-late-at-night-590297186.jpg',
  // date_join: '2015-10-21T18:27:50.000Z',
  // date_of_birth: 'Wed Oct 21 2015 17:21:30 GMT+0700 (Indochina Time)',
  // email: 'phuongvu@gmail.com',
  // facebook: 'xxxxxxfacebook',
  // fullname: 'Vũ Đỗ Phương',
  // local_id: 'TC62',
  // parent_email: 'xxxxxxparent_email',
  // parent_name: 'xxxxxxparent_name',
  // parent_phone: 'xxxxxxparent_phone',
  // phone_number: '123456789',
  // skype_id: 'xxxxxxskype_id',
  // zoom_id: 'xxxxxxzoom_id',
  // course_name: '',
  // course_str_date: 'Tue Dec 22 2020 09:19:59 GMT+0700 (Indochina Time)',
  // course_end_date: 'Tue Dec 22 2020 09:19:59 GMT+0700 (Indochina Time)',
  // mo_time_str: 'null',
  // mo_time_end: 'null',
  // tu_time_str: 'null',
  // tu_time_end: 'null',
  // we_time_str: 'null',
  // we_time_end: 'null',
  // th_time_str: 'null',
  // th_time_end: 'null',
  // fr_time_str: 'null',
  // fr_time_end: 'null',
  // sa_time_str: 'null',
  // sa_time_end: 'null',
  // su_time_str: 'null',
  // su_time_end: 'null'

  // req.files[0] =>
  // {
  //   fieldname: 'img',
  //   originalname: 'stock-photo-smiling-female-entrepreneur-working-from-home-late-at-night-590297186.jpg',
  //   encoding: '7bit',
  //   mimetype: 'image/jpeg',
  //   destination: './public/images',
  //   filename: 'img_1608603940020_297186.jpg',
  //   path: 'public\\images\\img_1608603940020_297186.jpg',
  //   size: 521179
  // }